name: OLX Scraper

on:
  push:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install webdriver-manager

      - name: Run scraper
        run: python scraper.py

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: olx-results
          path: results.csv
